name: CMake Build Matrix

on: [push]

# Env variables
env:
  BUILD_TYPE: Release
  
jobs:
  # Build for windows and mac (without sonar scanner)
  build-win-mac:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: "Windows"
            os: windows-latest
          - name: "Mac"
            os: macOS-latest
      
    steps:        
    - uses: actions/checkout@v2
          
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build
      
    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  
    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE
      
      
  # Build for windows and mac (without sonar scanner)
  build-linux:
    name: "Build linux and Sonar scan"
    runs-on: [ubuntu-latest]
      
    steps:        
    - uses: actions/checkout@v2
          
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build
    
    - name: Configure Sonar
      shell: bash
      run: |
        export SONAR_SCANNER_VERSION=4.2.0.1873
        export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
        curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip 
        unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
        mv $SONAR_SCANNER_HOME $HOME/.sonar/sonar
        curl --create-dirs -sSLo $HOME/.sonar/build-wrapper-linux-x86.zip https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
        unzip -o $HOME/.sonar/build-wrapper-linux-x86.zip -d $HOME/.sonar/
      
    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  
    - name: Build with sonar observer
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: $HOME/.sonar/build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir bw-output cmake --build . --config $BUILD_TYPE

    - name: Sonar scanner
      shell: bash
      run: $HOME/.sonar/sonar/bin/sonar-scanner -Dsonar.host.url=https://sonarcloud.io
      env:
        SONAR_SCANNER_OPTS: -server
